apiVersion: v1
kind: Pod
metadata:
  name: init-containers
spec:
  initContainers:
  - name: init-service
    image: ubuntu
    command: ['sh', '-c', "echo waiting for service; sleep 2"]
  - name: init-db
    image: ubuntu
    command: ['sh', '-c', "echo waiting for db; sleep 2"]
  containers:
  - name: app-container
    image: ubuntu
    command: ["/bin/bash"]