apiVersion: batch/v1
kind: Job
metadata:
  name: hello-world-job-fail
spec:
  backoffLimit: 2
  # 2 pods will be created until back off.
  template:
    spec:
      containers:
      - name: ubuntu
        image: ubuntu
        command:
          - "/bin/bash"
          - "-c"
          - "/bin/ech Hello from pod $(hostname) at $(date)"
      restartPolicy: Never